### ISSUE TITLE
custom Dataloaders

### ISSUE THREAD

**Issue by kaustubhroyvlabs** [naseemap47/YOLO-NAS#11]
Hi

I would like to get a peek at the structure of the dataloader used/the format in which the model expects input and write a custom dataloader in the format that supports the Trainer class.
Could you link me to a code/guide on how to write my own dataloader?

**Comment by naseemap47** [comment]
I don't know how to write a custom data-loader.
I used the function from **super_gradients** library for loading my data.

```
from super_gradients.training.dataloaders.dataloaders import coco_detection_yolo_format_train, coco_detection_yolo_format_val
```

**Comment by naseemap47** [comment]
> I don't know how to write a custom data-loader. I used the function from **super_gradients** library for loading my data.
> 
> ```
> from super_gradients.training.dataloaders.dataloaders import coco_detection_yolo_format_train, coco_detection_yolo_format_val
> ```

I think this will help you. So I am closing this issue.
If you have any questions please let me know and re-open this issue.
Thank you.

**Comment by ApodiAlsurihi** [comment]
Hello,
I am experiencing an issue while trying to load pre-trained weights for YOLO-NAS using the SuperGradients library.
Here is the code snippet I am using:

python
Copy code
from super_gradients.training import models

model = models.get('yolo_nas_s',
                   num_classes=len(dataset_params['classes']),
                   pretrained_weights="coco"
                   )
When I run this code, I get the following error:


Downloading: "https://sghub.deci.ai/models/yolo_nas_s_coco.pth" to C:\Users\Owner/.cache\torch\hub\checkpoints\yolo_nas_s_coco.pth
URLError: <urlopen error [Errno 11001] getaddrinfo failed>
It seems there is an issue with accessing the URL to download the pre-trained weights. I suspect it might be network-related, but I'm unsure if there are any alternative links or settings I need to change.
Any help or suggestions would be greatly appreciated!
Thank you in advance!

**Comment by naseemap47** [comment]
Hi @ApodiAlsurihi ,
I am also not able to find the model weights. I think they removed from the previous location.
Once I found the model weight. I will update here.
Thank you.
