### ISSUE TITLE
is there val check?

### ISSUE THREAD

**Issue by john09282922** [naseemap47/YOLO-NAS#19]

**Comment by naseemap47** [comment]
Hi @john09282922 ,
Please explain your issue briefly. 
Thank you.

**Comment by naseemap47** [comment]
Hi @john09282922 ,
I didn't added for validation data.
currently model val available for test data.
I will look into it. I will update this feature ASAP.
Thank you.

**Comment by naseemap47** [comment]
Hi @john09282922 ,
I updated the repo.
Now it will give validation and test results (if you have test data) after training.
I think it solve your problem.
Let me know if you have any problem or questions.
Thank you.
