### ISSUE TITLE
Training on two GPUs

### ISSUE THREAD

**Issue by yangguanghaiann** [naseemap47/YOLO-NAS#21]
How to train a model using two GPUs simultaneously to improve speed, the current program only supports training on one GPU. How to modify the train.py file to enable training on two GPUs simultaneously?

**Comment by naseemap47** [comment]
Hi @yangguanghaiann ,
I will look into it. Currently I didn't find any option to use more than one gpus.

**Comment by naseemap47** [comment]
Hi @yangguanghaiann ,
I updated the training code, now it can support more than one GPUs.
Only need to give `--gpus` args. It will automatically take all available GPUs.
I think this will solve your issue.
If have any other question and problem, Please let me know.
Thank you.
