### ISSUE TITLE
Yolo-nas change image size and pt save 

### ISSUE THREAD

**Issue by john09282922** [naseemap47/YOLO-NAS#23]
Hi, I would like to change image size of model when training Yolonas. And also save pt file, not ckpt file.
Is it possible?

**Comment by naseemap47** [comment]
Hi @john09282922 ,
I didn't find any option for changing image size.
If I find, I will  let you know.
Or if you find any option for that, Please let me know.
The Trainer class build by **super_gradients**, saving the model weight in the `.ckpt` format not `.pt`.
But its fine to use `.ckpt` format. It have same purpose as `.pt`.
Thank you.

**Comment by naseemap47** [comment]
Hi @john09282922 ,
I added option to change input image size. Please look into it.

model **.pt** have meta data (class names, model type, size, etc..) but **.pth** don't have.
But **super-gradients** didn't give feature for that. I also asked them for this. Currently not available.
If you find any please let me know.
But to over come this problem (class names), I manually added dummy loading for this.

If you have any questions and any improvements needed please let me know.
Thank you.
