### ISSUE TITLE
Training a quantized int8 version of yolo

### ISSUE THREAD

**Issue by nezarelkadyy** [naseemap47/YOLO-NAS#24]
How to make train a quantized int 8 version using the train script?

**Comment by naseemap47** [comment]
Hi @nezarelkadyy ,
Currently I didn't added int8 quantisation.
I am still searching on how to do that.
If I finds, I will let you know. or If you find any, please let me know.
Thank you.

**Comment by naseemap47** [comment]
Hi @nezarelkadyy  ,
I completed the development #49 
I am facing issue while running QAT.
`NameError: name 'SelectiveQuantizer' is not defined` https://github.com/Deci-AI/super-gradients/issues/1205#issuecomment-1606573396
They will fix this issue in the upcoming release. (https://github.com/Deci-AI/super-gradients/issues/1205#issuecomment-1612862427)
If you find any solution, please let me know.
Thank you.
