### ISSUE TITLE
Quantization aware training support

### ISSUE THREAD

**Issue by jeck00119** [naseemap47/YOLO-NAS#38]
Hi! It will be helpful if you could add CLI support for quantization aware training and maybe an option to save the model .pt because i want to use ultralytics for inference.
Thank you!

**Comment by naseemap47** [comment]
Hi @jeck00119 ,
I will be working on quantization aware training ASAP. I don't have time in this week, fully packed.
But I will look into it.
model **.pt** have meta data (class names, model type, size, etc..) but **.pth** don't have.
But **super-gradients** didn't give feature for that. I also asked them for this. Currently not available. 
If you find any please let me know.
But to over come this problem (class names), I manually added dummy loading for this.

If you have any questions and any improvements needed please let me know.
Thank you.

**Comment by hdiamond-foundationstack** [comment]
@naseemap47 Any update on quantization aware training?

**Comment by naseemap47** [comment]
@hdiamond-foundationstack If didn't get the time to complete. I will get it done ASAP.

**Comment by naseemap47** [comment]
Hi @jeck00119 @hdiamond-foundationstack ,
I completed the development #49 
I am facing issue while running QAT.
`NameError: name 'SelectiveQuantizer' is not defined` https://github.com/Deci-AI/super-gradients/issues/1205#issuecomment-1606573396
They will fix this issue in the upcoming release. (https://github.com/Deci-AI/super-gradients/issues/1205#issuecomment-1612862427)
If you find any solution, please let me know.
Thank you.
