### ISSUE TITLE
Why do I get an error when I use weights saved in the first training

### ISSUE THREAD

**Issue by wjli-debug** [naseemap47/YOLO-NAS#41]
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/1f081c46-c236-4906-aca7-5a71d3f9643a)
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/1d7cace3-1433-40f2-9082-081f30530be5)
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/0a54f3df-bc6b-4288-b1ce-1d2decb97d94)

**Comment by wjli-debug** [comment]
I also reported that the error weight path did not exist when I was inferring, but using the given execution statement on the command line only modified the model
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/b8a1f46f-9012-4138-ab1e-8f182c98d88a)

/root/anaconda3/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-08-10 15:56:40] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-08-10 15:56:40] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-08-10 15:56:40] WARNING - export.py - Failed to import pytorch_quantization
[2023-08-10 15:56:40] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
Traceback (most recent call last):
  File "/data1/yolonas/YOLO-NAS-master/inference.py", line 56, in <module>
    model = models.get(
  File "/root/anaconda3/lib/python3.9/site-packages/super_gradients/training/models/model_factory.py", line 219, in get
    ckpt_entries = read_ckpt_state_dict(ckpt_path=checkpoint_path).keys()
  File "/root/anaconda3/lib/python3.9/site-packages/super_gradients/training/utils/checkpoint_utils.py", line 153, in read_ckpt_state_dict
    raise FileNotFoundError(f"Incorrect Checkpoint path: {ckpt_path} (This should be an absolute path)")
FileNotFoundError: Incorrect Checkpoint path: /runs/train1/ckpt_best.pth (This should be an absolute path)

**Comment by naseemap47** [comment]
Hi @wjli-debug ,
Try with use absolute path for model weight and source path.
Let me know its working or NOT

**Comment by wjli-debug** [comment]
Ok, let me show you the error under the absolute path. It's the same problem. I tried to change the path of the weights in the train file by default, but obviously there was an error
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/c97c0335-308b-41ad-9ea8-f852ca6eacab)
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/297689d0-299a-492b-a2bd-a1fcfd7e4a63)

**Comment by wjli-debug** [comment]
Ok, let me show you the error under the absolute path, the same problem, I tried to change the path of the default weight in the train file, but apparently the same error occurred
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/1410dfa8-02ab-4ce1-8120-a236629909b7)
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/9f5ae2b3-1d82-47a8-a88e-9b49af9ac25a)

**Comment by naseemap47** [comment]
Hi @wjli-debug ,
I think its the issue with 
`--weight /data1/yolonas/YOLO-NAS-master/runs/train1/ckpt_best.pth`
I think this is making issue.
`--weight /data1/..`
its should be like 
`--weight runs/train1/ckpt_best.pth`
**OR**
`--weight home/username/.../data1/yolonas/YOLO-NAS-master/runs/train1/ckpt_best.pth`
Let me know its working or NOT

**Comment by naseemap47** [comment]
Hi @wjli-debug ,
I think its solve your issue. So that I am closing this issue.
If you have any issue or question, please reopen this issue.
Thank You

**Comment by wjli-debug** [comment]
--weight runs/train1/ckpt_best.pth, I have tried this way, I developed the corresponding result graph there, but it failed, the absolute path of other projects on my server starts from /data1, it is valid, but in this project it did not succeed. Is there something wrong with the code when the path is read?
![image](https://github.com/naseemap47/YOLO-NAS/assets/116251731/2f20ab51-062f-4c24-9938-57d615a8ce67)

**Comment by naseemap47** [comment]
Hi @wjli-debug ,
Its working for me. I didn't face any issue.
Where you are running your code ?
I think you not giving correct path !

### My Suggestion
I think you are using **ubuntu virtual machine**.
This is very slow and outdated, you can use **docker** instead.
It will faster and easy.
