### ISSUE TITLE
error in train my dataset

### ISSUE THREAD

**Issue by oussaifi-majdi** [naseemap47/YOLO-NAS#5]
i have this error when i train my dataset

 if __name__ == '__main__':
            freeze_support()
            ...

    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.

**Comment by naseemap47** [comment]
Can you share me your dataset format
Check its in the COCO YOLO format

**Comment by oussaifi-majdi** [comment]
![image](https://github.com/naseemap47/YOLO-NAS/assets/31904454/94f8c499-f013-4178-bb40-33522781894e)

**Comment by naseemap47** [comment]
I think its the issue with your **data.yaml**
Checkout my **data.yaml** file: _**https://github.com/naseemap47/YOLO-NAS/blob/master/data.yaml**_

**Comment by Andrewhsin** [comment]
I also have this problem too , my format is yolo

This is my screen image
![AnyConv com__awesun_20230519145834](https://github.com/naseemap47/YOLO-NAS/assets/59113940/64066d61-9d27-4a87-a2f0-08e789eb6251)
![AnyConv com__awesun_20230519145856](https://github.com/naseemap47/YOLO-NAS/assets/59113940/541a0f40-7af4-4fd3-a13c-f56e10036b6a)
![AnyConv com__awesun_20230519145909](https://github.com/naseemap47/YOLO-NAS/assets/59113940/23b7dfd3-7608-45ae-8878-877e3ed512c4)

**Comment by naseemap47** [comment]
Can you share your repository or data, So that I can check what is the issue.

**Comment by naseemap47** [comment]
I think the issue with windows path format,
In Linux or Mac its look like: `/home/path`
But in Windows, its look like: `\User\Downloads`
I didn't face issue, I think its due to my OS is Ubuntu

**Comment by naseemap47** [comment]
@oussaifi-majdi @Andrewhsin 
Try with google colab, it will work.

**Comment by Andrewhsin** [comment]
I copy this code on my file , it’s work!


if __name__ == '__main__':
     # train code

**Comment by naseemap47** [comment]
Thank you @Andrewhsin for using my repository and solving this issue.
If you have any feedback let me know.
Hope problem solved for @oussaifi-majdi
So, I am closing this issue.
