### ISSUE TITLE
Running into problem while using inference for webcam

### ISSUE THREAD

**Issue by Sumeshbaba** [naseemap47/YOLO-NAS#53]
Hello Naseem, good afternoon!

Wonderful work with this project! Makes implementation much easier.

But, when I try to run the inference code with webcam, this is the error I get

[ WARN:0@14.959] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (464) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -2147024809

[ WARN:0@14.964] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (476) `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -2147024809

[ WARN:1@14.966] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1752) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147024809

[INFO] Failed to read...

I tried downgrading OpenCv-Python, and different versions as well, still running into the same error! Could you help me with this?

Also, on another note, running the inference on a video gives me around 5-6 fps, which seems quite low. My GPU is RTX 3060. What could be causing this? I tried batch.py inference as well, but it does not display any fps information. Is there any flags I've to pass like --gpu 0 to make sure it utilizes GPU?

Thanks a lot!

**Comment by naseemap47** [comment]
Can you share the code you used for inference using webcam.
Did you installed CUDA and NVIDIA Drivers ?

**Comment by Sumeshbaba** [comment]
Hello Naseem, thanks for your reply.

I've used the same inference.py code that you've shared in the repository.
I change source 0 for utilising the webcam.

Also, have you tested this code on any GPU? What is the fps you got while
running inference? Meanwhile, I'll double check for CUDA installation

**Comment by naseemap47** [comment]
Did you try with other sources like video and RTSP ?
Or this issue only for webcam ?

Check CUDA installation using PyTorch
```
>>> import torch
>>> torch.cuda.is_available()
True
```

**Comment by Sumeshbaba** [comment]
Hello Naseem,

Yes, I tried it for a video on my local disk, and it worked fine. The
inference only fails while testing for a webcam. I have not tried RTSP,
since it is not my use case. Also, CUDA installation outputs true, so GPU
is available. But the fps is about 5-6, which is quite less.

What might be causing this low FPS and webcam problem?

**Comment by naseemap47** [comment]
Try testing webcam without model.
```
# import the opencv library 
import cv2 


# define a video capture object 
vid = cv2.VideoCapture(0) 

while(True): 
	
	# Capture the video frame 
	# by frame 
	ret, frame = vid.read() 

	# Display the resulting frame 
	cv2.imshow('frame', frame) 
	
	# the 'q' button is set as the 
	# quitting button you may use any 
	# desired button of your choice 
	if cv2.waitKey(1) & 0xFF == ord('q'): 
		break

# After the loop release the cap object 
vid.release() 
# Destroy all the windows 
cv2.destroyAllWindows() 
```

Let me know this is working for you or not ?

Can you share your model, If possible.
So that I can test it from my side.

**Comment by Sumeshbaba** [comment]
Hello Naseem, thanks for the quick responses!

I tried testing the camera without the model using the above code, and it didn't work. Probably some error with the drivers or software updates. I'll try to figure out what is causing this hardware problem.

Another question Naseem, this code seems to be compatible only with Super_gradients with 3.1.3. It runs into errors with the current versions of super_gradients. Any plan to make it compatible?

Also, could you replicate the issue with inference speed on your side? Sorry, I cannot share the model in public domain yet. But could you test it on maybe generic coco dataset and get back to me? Thanks a lot!

**Comment by naseemap47** [comment]
Hi @Sumeshbaba ,
I didn't update the code for latest super_gradients. When I get time will do that ASAP.
I test the Inference speed from my side.

**Comment by Sumeshbaba** [comment]
Thanks a lot, Naseem. Do test the inference speed and let me know the observations!

Good luck with updating the repository for latest super_gradients version!

**Comment by naseemap47** [comment]
I am getting 10-12 FPS.
While you inference on video check your GPU usage.
```
watch -n 1 nvidia-smi
```
run this in a new terminal to get GPU usage.

**Comment by Sumeshbaba** [comment]
Thank you Naseem for confirming the speed!

I checked the GPU usage, and it is being utilized while the inference is running. Maximum I get is about 7 fps for some frame. But I think this is a known issue with YOLO-NAS while utilizing PyTorch framework. 

Hope they can increase inference speed on PyTorch with upcoming upgrades.

**Comment by naseemap47** [comment]
@Sumeshbaba 
I am closing this issue.
If you have any issues please let know.
Thank you
