### ISSUE TITLE
Support to export onnx model with/without quantinzation

### ISSUE THREAD

**Issue by rose-jinyang** [naseemap47/YOLO-NAS#54]
Hello
How are you?
Thanks for contributing to this project.
Could you support to export onnx model with/without quantization and do inference of the exported onnx model?
Thanks

**Comment by naseemap47** [comment]
Hi @rose-jinyang ,
Thank you for your feedback. I will add ONNX option ASAP.
If you have any issues or requirements. Please let me know.
Thank you.

**Comment by naseemap47** [comment]
Hi @rose-jinyang ,
To export and inference ONNX model
https://docs.deci.ai/super-gradients/latest/documentation/source/models_export.html
Please look into that.
I think this will solve your issue.
If you have any issue any issues. Please let me know.
Thank you.
