### ISSUE TITLE
Yolo dataset format

### ISSUE THREAD

**Issue by errors4o4** [naseemap47/YOLO-NAS#55]
Does the `train.py` code accommodate YOLO format datasets, or is it exclusively designed for datasets in JSON format?
![image](https://github.com/naseemap47/YOLO-NAS/assets/81018286/0a532569-bb83-48b9-bf18-22b33ba97d61)

**Comment by naseemap47** [comment]
Hi @errors4o4 ,
Currently is it exclusively designed for datasets in JSON format.
You can convert your YOLO format to JSON:
https://github.com/naseemap47/YOLO-NAS?tab=readme-ov-file#-prepare-dataset
