### ISSUE TITLE
Torch and Torch-quantization module mismtach 

### ISSUE THREAD

**Issue by IamShubhamGupto** [naseemap47/YOLO-NAS#56]
Hello !

Thank you for making this repository, it has been very helpful with my research. I came across an error which is fully documented and solved in the following issue - https://github.com/Deci-AI/super-gradients/issues/1045#issuecomment-1690484940

The problem being torch 1.12 and torch-quantization 2.1.2 are incompatible so we need to downgrade to torch 1.11 which resolves the issue. 

The requirements and the readme need to be updated to reflect the same

**Comment by naseemap47** [comment]
Hi @IamShubhamGupto ,
Thank you for finding this issue.
I actually forgot to update my installation requirements.
I did correctly for docker setup.
I am updating the requirements.
