### ISSUE TITLE
Github link provided is for auto annotater. 

### ISSUE THREAD

**Issue by suku47** [naseemap47/YOLO-NAS#58]
Github link provided to convert Yolo label txt files to JSON is auto annotater. I didn't find way to convert into JSON. Correct me If I am wrong.

**Comment by naseemap47** [comment]
Hi @suku47 ,
https://github.com/naseemap47/autoAnnoter/tree/master/tools#10-yolo_to_jsonpy
this will convert Yolo label txt files to JSON.
If any issues, please let me know
