### ISSUE TITLE
While runing inference.py

### ISSUE THREAD

**Issue by giriprasad51** [naseemap47/YOLO-NAS#9]
File "inference.py", line 96, in <module>
    preds = next(model.predict(img_rgb, conf=args['conf'])._images_prediction_ls
t)
  File "/data/users/giri_prasad/custom/super-gradients/src/super_gradients/train
ing/models/detection_models/customizable_detector.py", line 176, in predict  
    return pipeline(images)  # type: ignore
  File "/data/users/giri_prasad/custom/super-gradients/src/super_gradients/training/pipelines/pipelines.py", line 96, in __call__
    return self.predict_images(inputs, batch_size)
  File "/data/users/giri_prasad/custom/super-gradients/src/super_gradients/training/pipelines/pipelines.py", line 111, in predict_images
    return self._combine_image_prediction_to_images(result_generator, n_images=len(images))
  File "/data/users/giri_prasad/custom/super-gradients/src/super_gradients/training/pipelines/pipelines.py", line 290, in _combine_image_prediction_to_images
    images_predictions = [next(iter(images_predictions))]
  File "/data/users/giri_prasad/custom/super-gradients/src/super_gradients/training/pipelines/pipelines.py", line 149, in _generate_prediction_result
    yield from self._generate_prediction_result_single_batch(batch_images)

**Comment by giriprasad51** [comment]
python3 inference.py --data ./data.yaml --model yolo_nas_m --weight ./runs/train0/ckpt_best.pth --source /home/giriprasad/custom/videos/1.mp4 --conf 0.66

**Comment by naseemap47** [comment]
can you share your model.
So that I can test and try to find out the problem.

**Comment by naseemap47** [comment]
Hi @giriprasad51, did you fix your issue with inference your model.

**Comment by giriprasad51** [comment]
Nope still working

**Comment by naseemap47** [comment]
@giriprasad51, sorry  didn't I understand what you are saying.
I you didn't fix the issue, please share your model via **Google drive** or any other medium.
Thank you.

**Comment by giriprasad51** [comment]
https://drive.google.com/file/d/15dSZJKdnrgzd6AoBZBAi9GZ2ZFPRd8TO/view?usp=share_link

**Comment by naseemap47** [comment]
@giriprasad51 
Can you share your **data.yaml** file.

**Comment by giriprasad51** [comment]
names:
- cylinder   
- machine_gun  
- mask  
- pistle  
- knife  
- helmet  
- Axe  
- Sword  
Dir: '/data/users/giri_prasad/data1/'
images:
  test: test/images
  train: train/images
  val: val/images
labels:
  test: test/labels
  train: train/labels
  val: val/labels

**Comment by naseemap47** [comment]
> @giriprasad51 your model is working find. I didn't got any errors. I think its the issue the versions of libraries. **Can you share your library versions**. Are you using **conda environment**, if yes please share the **versions libraries installed** in that.
> 
> ### Suggestion from my side.
> Create a new conda environment and install all libraries required.
> 
> ```
> conda create -n nas python=3.9 -y
> conda activate nas
> conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch -y
> pip install triton==2.0.0
> pip install super-gradients
> ```
> 
> Then try to run your model. Please let me know your updates and questions. Thank you.

I think this will help you. So I am closing this issue.
If you have any questions please let me know and re-open this issue.
Thank you.
